export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const SET_ACTIVE_CLUE = "SET_ACTIVE_CLUE";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const CHANGE_STAGE = "CHANGE_STAGE";
export const UPLOAD_CONFIG = "UPLOAD_CONFIG";
export const SET_CLUE_VIEWED = "SET_CLUE_VIEWED";
