export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const SET_ACTIVE_CLUE = "SET_ACTIVE_CLUE";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const CHANGE_STAGE = "CHANGE_STAGE";

export const UPLOAD_SINGLE_JEOPARDY = "UPLOAD_SINGLE_JEOPARDY";
export const UPLOAD_DOUBLE_JEOPARDY = "UPLOAD_DOUBLE_JEOPARDY";
export const UPLOAD_FINAL_JEOPARDY = "UPLOAD_FINAL_JEOPARDY";
// export const VIEW_CLUE = "VIEW_CLUE";
